[package]
name = "venom-of-neptune"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal = "0.2.7"
nb = "1"
cortex-m = "0.7.6"
cortex-m-rt = "0.7.1"
# Panic behaviour, see https://crates.io/keywords/panic-impl for alternatives
panic-halt = "0.2.0"
rtt-target = "0.6.1"
embedded-hal-compat = "0.13.0"
stm32f1xx-hal = "0.11.0"
